### ISSUE TITLE
Add bee count update to Shipment interface

### ISSUE THREAD

**Issue by dmksystems** [DROCCK/oh-behive#16]
Subtract fromYard
Add ToYard
Complete button make active or inactive.

**Comment by chaithao** [comment]
I'm unsure what "Complete button make active or inactive" is for. Are we supposed to create a button "complete" in which toggles active/inactive status? and whats the purpose of bee count? number of bees maybe or number of times a function is called? more details on issues would be nice.

I added some stuff to shipment in my local branch but have not pushed yet since i'm unsure of the purpose of bee count, so my stuff could be unnecessary.

**Comment by dmksystems** [comment]
Creating a shipment will subtract from the number of hives at a yard then
when you hit complete it will add the hives to the new yard and mark the
shipment as inactive or complete

**Comment by chaithao** [comment]
Okay, makes sense, thanks.

**Comment by chaithao** [comment]
So, I keep getting a null pointer exception when I try to manipulate data in shipment object through controller or service at the same time the create button is invoked to save. Does anyone know if its a problem to try and do this? for example maybe we can't manipulate the data this way because all we can do is manipulate the database.

**Comment by dmksystems** [comment]
It is probably because there is no initial value to subtract from

**Comment by chaithao** [comment]
i'm using the shipment object's "to" and "from" yards data which seem to be in the database because its always loaded when you bring up the yard screen. I'm also assuming that the specific shipment data are set in the shipment object before invoking save(shipment).

**Comment by celison** [comment]
The singles and doubles haven't yet been implemented into yard, that data fields are there in the Yard class but it they are not yet set in the forms, so you will get a null value when trying to get the singles or doubles.

**Comment by chaithao** [comment]
Okay makes sense. I just tried using maxHives from the yards in shipment to add/subtract with the singles+doubles from shipment and i'm still getting null exception. I'll continue to mess around with it.

**Comment by chaithao** [comment]
Do we want to delete shipments once they are completed? or just lock them somehow?

**Comment by dmksystems** [comment]
Mark them as completed

**Comment by chaithao** [comment]
Status was added to shipment and can be changed through updates. Shipment now increments/decrements specified yards upon being created and completed.
